### ISSUE TITLE
Error: Input string was not in the correct format

### ISSUE THREAD

**Issue by Koxik-yt** [takkun-mint/FallGuysTools#16]
![image](https://github.com/user-attachments/assets/1a62b3c0-b371-499f-b0d3-3798e111644c)
I tried reinstalling, restarting, nothing seems to work.

And sometimes it gives me the forced update due to missing files
![image](https://github.com/user-attachments/assets/c084aa31-0cb2-4415-9a2e-9641e2b2ae94)

After that it says that download is complete and that I should reboot, I reboot and I get this:
![image](https://github.com/user-attachments/assets/e2ec2846-e43a-4c68-abfe-b8545a40af28)

**Comment by takkun-mint** [comment]
Hello.
Thank you for using this site.
We have implemented an update to output detailed information on the issue in question.
Please start Tools once, and after it is started after the exit due to initial setup error, you will see the forced update.
This is normal operation.
We would like to ask you to reinstall from GitHub or update using the above method and do the following.

When an error occurs regarding the initial setup
in the bin folder of the Tools installation folder.
There are the files “StageInfo.csv” and “ToolSettings.csv”.
I would like you to copy those files to another location before OKing the message box and exiting.
You will also find “ToolLog.txt” and “ToolLog-prev.txt” directly under the Tools folder.
We would like you to attach them along with the copy you made.
Sorry for the delay in replying.
Thank you for your continued support.

**Comment by Koxik-yt** [comment]
> Please start Tools once, and after it is started after the exit due to initial setup error, you will see the forced update.
This is normal operation.
We would like to ask you to reinstall from GitHub or update using the above method and do the following.

Tried both, didnt work, still getting same errors. 

Here are the files:
[ToolLog.txt](https://github.com/user-attachments/files/17085733/ToolLog.txt)
[ToolLog-prev.txt](https://github.com/user-attachments/files/17085734/ToolLog-prev.txt)
[StageInfo.csv](https://github.com/user-attachments/files/17085736/StageInfo.csv)
[ToolSettings.csv](https://github.com/user-attachments/files/17085737/ToolSettings.csv)

**Comment by takkun-mint** [comment]
Thanks for the information.
It may be caused by language settings.
To be verified here,
Can you tell us what language your PC uses?

**Comment by Koxik-yt** [comment]
> Can you tell us what language your PC uses?

My PC uses polish.
Do i try to change it to (english to) see if it works?

**Comment by Koxik-yt** [comment]
I can confirm that it works after i changed language of my PC, but would be better if it worked on polish too.

**Comment by takkun-mint** [comment]
Thanks for the information.
I understand that it did not work in Polish, but it did work in English.
We will sort out the situation and start working on a fix.
I will let you know when the fix is completed.

**Comment by Koxik-yt** [comment]
Thanks for ur help

**Comment by Koxik-yt** [comment]
It works after updating, 
altho the Avast thought it s a virus at first, on a second scan it said everything s ok.

Since it s fixed now, I m gonna close the issue. Thanks for all the help.
